<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>
    <h4>
        <span><?php echo count($_items) ?><?php /* @escapeNotVerified */echo __(" review(s) for "); ?></span><strong><?php echo $block->escapeHtml($block->getProduct()->getName()) ?></strong>
    </h4>
    <div class="block review-list" id="customer-reviews">
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_review): ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <div class="author-avatar">
                            <img src="<?php echo $block->getViewFileUrl('images/customer-avatar-demo.png'); ?>" alt="" />
                        </div>
                        <div class="review-content" itemprop="description">
                            <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong><span class="review-details-label"><?php /* @escapeNotVerified */
                                echo __(' - ') ?></span>
                            <time class="review-details-value" itemprop="datePublished"
                                  datetime="<?php /* @escapeNotVerified */
                                  echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */
                                echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
                            <div class="review-details"><?php echo nl2br($block->escapeHtml($_review->getDetail())) ?></div>
                            <?php if (count($_review->getRatingVotes())): ?>
                                <div class="review-ratings">
                                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                        <div class="rating-summary item" itemprop="reviewRating" itemscope
                                             itemtype="http://schema.org/Rating">
                                        <span
                                            class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>

                                            <div class="rating-result" title="<?php /* @escapeNotVerified */
                                            echo $_vote->getPercent() ?>%">
                                                <meta itemprop="worstRating" content="1"/>
                                                <meta itemprop="bestRating" content="100"/>
                            <span style="width:<?php /* @escapeNotVerified */
                            echo $_vote->getPercent() ?>%">
                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */
                                    echo $_vote->getPercent() ?>%</span>
                            </span>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif; ?>
