<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */
?>
<div class="mb-forgetpassword-popup" style="display:none;">
    <div class="mb-login-popup-title">
        <span class="mb-login-popup-title-logo">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <strong><?php echo __('Reset Password'); ?></strong>
    </div>
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-forgotpassword">
        <form class="form forgotpassword"
              method="post"
              id="forgetpassword-form"
              enctype="multipart/form-data" autocomplete="off">
            <fieldset class="fieldset" data-hasrequired="<?php echo __('* Required Fields') ?>">
                <div
                        class="field note"><?php echo __('To have your password reset, enter your email address below. We will then send an email containing a link to reset your password.'); ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" class="input-text"
                               value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
            </fieldset>
            <div class="actions">
                <div class="">
                    <button type="submit" class="action submit primary"><span><?php echo __('Reset Password') ?></span>
                    </button>
                </div>
            </div>
            <div class="actions">
                <div class="secondary">
                    <a class="action back" href="<?php echo $block->getLoginUrl() ?>">
                        <span class="mb-back-link"><?php echo __('Login') ?></span>
                    </a>
                </div>
                <span> | </span>
                <div class="secondary">
                    <a class="action mb-create-account" href="<?php echo $block->getUrl('customer/account/create'); ?>">
                        <span><?php echo __('Create an Account') ?></span>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>