<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 */
?>
<?php $_product = $block->getProduct(); ?>
<div class="mb-login-popup-title center">
    <div class="mb-login-popup-title">
        <strong><?php echo __('You failed to add product to the comparison list.'); ?></strong>
    </div>
</div>
<div class="ajaxcompare-success-box">
    <p class="message-error">
        <!--NOTHING-->
    </p>
    <h2 class="product-name"><?php echo $_product->getName() ?></h2>
    <?php echo $block->getChildHtml('product_image', true); ?>
    <div class="ajaxcompare-buttons">
        <button type="button" id="ajaxcompare_btn_close_popup" class="action primary mb-ajaxsuite-close"
                title="<?php echo __('Close') ?>">
            <span><?php echo __('Close ') ?></span>
            <?php
            if ($popupTTL = $this->helper('Tigren\Ajaxsuite\Helper\Data')->getTTLAjaxSuite()) {
                ?>
                (<span class="ajaxsuite-autoclose-countdown"><?php echo $popupTTL ?></span>)
                <?php
            }
            ?>
        </button>
        <button type="button" id="ajaxcompare_btn_to_login" class="action focus primary"
                title="<?php echo __('Login') ?>">
            <span><?php echo __('Login') ?></span>
        </button>
    </div>
</div>