<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */

// @codingStandardsIgnoreFile

?>
<?php
$_product = $block->getProduct();
$buttonTitle = __('Add to Wishlist');
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */
                               echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */
                               echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="button" title="Cancel" class="action primary mb-ajaxsuite-close"
                        id="ajaxwishlist_btn_cancel">
                    <span><?php echo __('Cancel') ?></span>
                </button>
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action ajax-popup-to-cart primary"
                        id="product-addtogroup-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
                </button>
            </div>
        </div>
    </div>
<?php endif; ?>
