<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 */
?>

<?php
$_productCollection = $block->getNewProductsCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$image = 'category_page_grid';
$mode = 'grid';
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="block block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="row">
                    <?php $iterator = 1; ?>
                    <?php foreach ($_productCollection as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-md-4 item">' : '</li><li class="col-md-4 item">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPrice($_item);
                                ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
