<?php $parentCategoryId = $block->getData('category_id'); ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $parentCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($parentCategoryId);
    $subCats = $parentCategory->getChildrenCategories();
?>
<div class="category-product-tab" id="category_<?php echo $parentCategoryId ?>_tab"> <!-- Fill category id in here to set unique value -->
    <div class="tab-title">
        <h4><?php echo $parentCategory->getName();?></h4>
        <ul>
            <?php foreach($subCats as $sub_category):?>
                <li><a href="#sub_cat_<?php echo $sub_category->getId();?>"><?php echo $sub_category->getName();?></a></li>
            <?php endforeach ?>
        </ul>
        <a class="view-all" href="<?php echo $parentCategory->getUrl();?>"><?php /* @escapeNotVerified */ echo __('View All') ?> &raquo;</a>
    </div>
    <div class="tab-content">
        <?php foreach($subCats as $sub_category):?>
            <div id="sub_cat_<?php echo $sub_category->getId();?>">
                <div class="row">
                    <div class="col-md-9">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tigren_techstore_home_category_tab_content')->toHtml();?>
                    </div>
                    <div class="col-md-3 sales-by-brands"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tigren_techstore_top_sales_by_brand')->toHtml();?></div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function($){
            $( "#category_<?php echo $parentCategoryId ?>_tab" ).tabs({
                beforeLoad: function( event, ui ) {
                    ui.jqXHR.fail(function() {
                        ui.panel.html(
                            "Couldn't load this tab. We'll try to fix this as soon as possible. " +
                            "If this wouldn't be a demo." );
                    });
                }
            });
        });
    </script>
</div>