<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */
?>
<?php
$popupHtmlId = $block->getPopupHtmlId();
$popupTitle = $block->getData('popup_title');
$contactDescription = $block->getData('contact_description');
?>

<div id=<?php echo $popupHtmlId ?> class="mb-popup-container mb-no-view">
<div class="mb-popup-border">
    <div class="mb-popup-title"><strong><?php echo $popupTitle; ?></strong></div>
    <div class="mb-popup-full mb-contact-container">
        <div class="mb-contact-description"><span><?php /* @escapeNotVerified */
                echo $contactDescription ?></span></div>
        <form class="form contact mb-contact-form"
              action="<?php /* @escapeNotVerified */
              echo $block->getContactusFormActionUrl(); ?>"
              id="contact-form"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */
              echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="name"><span><?php /* @escapeNotVerified */
                            echo __('Name') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?php /* @escapeNotVerified */
                        echo __('Name') ?>"
                               value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                               class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */
                            echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?php /* @escapeNotVerified */
                        echo __('Email') ?>"
                               value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                               class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone"><span><?php /* @escapeNotVerified */
                            echo __('Phone Number') ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */
                        echo __('Phone Number') ?>" value="" class="input-text" type="text"/>
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="comment"><span><?php /* @escapeNotVerified */
                            echo __('What’s on your mind?') ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */
                        echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3"
                                  data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button type="submit" title="<?php /* @escapeNotVerified */
                    echo __('Submit') ?>" class="action submit primary">
                        <span><?php /* @escapeNotVerified */
                            echo __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>

<script>
require([
    'jquery',
    'mage/mage',
    'tigren/popup'
], function ($) {
    "use strict";
    $(document).ready(function($) {
        $('body').mbPopup({
            enabled_statistics: <?php echo $block->isEnabledStatistics() ?>,
            impression_url: '<?php echo $block->getImpressionActionUrl() ?>',
            instance_id: '<?php echo $block->getInstanceId() ?>',
            popup_class: 'mb-popup-custom-contact-form',
            content : $('#<?php echo $popupHtmlId ?>').html(),
            popup_id: '<?php echo $popupHtmlId ?>',
            cookie_expires : '<?php echo $block->getData('cookie_expires') ?>',
            border_radius: '<?php echo $block->getData('border_radius') ?>' + '%',
            popup_width: '<?php echo $block->getData('popup_width') == 'auto' ? $block->getData('popup_width') : $block->getData('popup_width') . 'px' ?>',
            animate: '<?php echo $block->getData('popup_effect') ?>',
            view_session: '<?php echo $block->getData('view_session') ?>',
            view_seconds: '<?php echo $block->getData('view_seconds') ?>',
            auto_close: '<?php echo $block->getData('auto_close') ?>'
        });
    });
});

</script>