<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */
?>
<?php
$popupHtmlId = $block->getPopupHtmlId();
$popupTitle = $block->getData('popup_title');
$loginDescription = $block->getData('login_description');
?>

<div id=<?php echo $popupHtmlId ?> class="mb-popup-container mb-no-view">
<div class="mb-popup-border">
    <div id="mb-popup-notice-cookie-block">
        <div class="content">
            <p>
                <strong><?php /* @escapeNotVerified */
                    echo __('We use cookies to make your experience better.') ?></strong>
                <span><?php /* @escapeNotVerified */
                    echo __('To comply with the new e-Privacy directive, we need to ask for your consent to set the cookies.') ?></span>
                <?php /* @escapeNotVerified */
                echo __('<a href="%1">Learn more</a>.', $block->getPrivacyPolicyLink()) ?>
            </p>
            <div class="actions">
                <button id="mb-popup-btn-cookie-allow" class="action allow primary">
                    <span><?php /* @escapeNotVerified */
                        echo __('Allow Cookies'); ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
</div>

<script>
require([
    'jquery',
    'mage/mage',
    'tigren/popup'
], function ($) {
    "use strict";
    $(document).ready(function($) {
        $('body').mbPopup({
            enabled_statistics: <?php echo $block->isEnabledStatistics() ?>,
            impression_url: '<?php echo $block->getImpressionActionUrl() ?>',
            instance_id: '<?php echo $block->getInstanceId() ?>',
            popup_class: 'mb-popup-custom-contact-form',
            content : $('#<?php echo $popupHtmlId ?>').html(),
            popup_id: '<?php echo $popupHtmlId ?>',
            cookie_expires : '<?php echo $block->getData('cookie_expires') ?>',
            border_radius: '<?php echo $block->getData('border_radius') ?>' + '%',
            popup_width: '<?php echo $block->getData('popup_width') == 'auto' ? $block->getData('popup_width') : $block->getData('popup_width') . 'px' ?>',
            animate: '<?php echo $block->getData('popup_effect') ?>',
            view_session: '<?php echo $block->getData('view_session') ?>',
            view_seconds: '<?php echo $block->getData('view_seconds') ?>',
            auto_close: '<?php echo $block->getData('auto_close') ?>',
            cookieNoticesConfig: {
                'cookieAllowButtonSelector': '#mb-popup-btn-cookie-allow',
                'cookieName': '<?php /* @escapeNotVerified */
    echo \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>',
                'cookieValue': <?php /* @escapeNotVerified */
    echo $this->helper('Magento\Cookie\Helper\Cookie')->getAcceptedSaveCookiesWebsiteIds() ?>,
                'cookieLifetime': <?php /* @escapeNotVerified */
    echo $this->helper('Magento\Cookie\Helper\Cookie')->getCookieRestrictionLifetime() ?>,
                'noCookiesUrl': '<?php /* @escapeNotVerified */
    echo $block->getUrl('cookie/index/noCookies') ?>'
            }
        });
    });
});

</script>