<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */
?>
<?php
$popupHtmlId = $block->getPopupHtmlId();
$popupTitle = $block->getData('popup_title');
$newsletterDescription = $block->getData('newsletter_description');
?>

<div id=<?php echo $popupHtmlId ?> class="mb-popup-container mb-no-view">
<div class="mb-popup-border">
    <div class="mb-popup-title"><strong><?php echo $popupTitle; ?></strong></div>
    <div class="mb-popup-full mb-newsletter-container">
        <div class="mb-newsletter-description"><span><?php /* @escapeNotVerified */
                echo $newsletterDescription ?></span></div>
        <form class="form subscribe mb-newsletter-form"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getNewsletterFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="mb-newsletter-email">
                <input name="email" type="email" id="newsletter"
                       placeholder="<?php /* @escapeNotVerified */
                       echo __('Enter your email address') ?>"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
            <div class="mb-newsletter-subscribe actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */
                        echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
</div>

<script>
require([
    'jquery',
    'mage/mage',
    'tigren/popup'
], function ($) {
    "use strict";
    $(document).ready(function($) {
        $('body').mbPopup({
            enabled_statistics: <?php echo $block->isEnabledStatistics() ?>,
            impression_url: '<?php echo $block->getImpressionActionUrl() ?>',
            instance_id: '<?php echo $block->getInstanceId() ?>',
            popup_class: 'mb-popup-custom-newsletter',
            content : $('#<?php echo $popupHtmlId ?>').html(),
            popup_id: '<?php echo $popupHtmlId ?>',
            cookie_expires : '<?php echo $block->getData('cookie_expires') ?>',
            border_radius: '<?php echo $block->getData('border_radius') ?>' + '%',
            popup_width: '<?php echo $block->getData('popup_width') == 'auto' ? $block->getData('popup_width') : $block->getData('popup_width') . 'px' ?>',
            animate: '<?php echo $block->getData('popup_effect') ?>',
            view_session: '<?php echo $block->getData('view_session') ?>',
            view_seconds: '<?php echo $block->getData('view_seconds') ?>',
            auto_close: '<?php echo $block->getData('auto_close') ?>'
        });
    });
});

</script>